# Tomcat
server:
  port: 8080

spring:
  # 环境 dev|docker|prod
  profiles:
    active: docker
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  #解决swaggerUI不匹配接口
swagger:
  enable: true
  title: JavaSecLib后端 API
  description: API 描述
  version: 5.0.0
  author: whgojp
  url: https://blog.csdn.net/weixin_53009585
  email: whgojp@foxmail.com
management:
  # 端点信息接口使用的端口，为了和主系统接口使用的端口进行分离
  server:
    port: 9090
  # 端点健康情况，默认值"never"，设置为"always"可以显示硬盘使用情况和线程情况
  endpoint:
    health:
      show-details: always
  # 设置端点暴露的哪些内容，默认["health","info"]，设置"*"代表暴露所有可访问的端点
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /sys/actuator

logging:
  config: classpath:logback-spring.xml

# mybaits-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: /mapper/**/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false