server:
  port: 80

spring:
  # 环境 dev|docker
  profiles:
    active: docker
  thymeleaf:
    mode: LEGACYHTML5 #模板类型
    cache: false #缓存
    encoding: utf-8 #编码
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  #解决swaggerUI不匹配接口
#    view:                                  # 设置JSP视图的前缀和后缀
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp

swagger:
  enable: true
  title: JavaSecLib后端 API
  description: API 描述
  version: 5.0.0
  author: whgojp
  url: https://blog.csdn.net/weixin_53009585
  email: whgojp@foxmail.com
management:
  # 端点信息接口使用的端口，为了和主系统接口使用的端口进行分离
  server:
    port: 80
  # 端点健康情况，默认值"never"，设置为"always"可以显示硬盘使用情况和线程情况
  endpoint:
#    gateway:
#      enabled: true
    health:
      show-details: always
  # 设置端点暴露的哪些内容，默认["health","info"]，设置"*"代表暴露所有可访问的端点
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /sys/actuator

logging:
  config: classpath:logback-spring.xml

# mybaits-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: /mapper/**/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false

folder:
  upload: /tmp/upload
  static: /tmp/static

rsa:
  private:
    key: "-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDtttbAHKH8paAM
bVChMxlQ900ZDIamD4k00Y0aSzIF03dXFkO3+1oFKYj3DDwa68G0XGOJOoRkpfYK
LZdD45/2D32vcCb2tLzh9jFM79KG4+r+eflkQAMmCBAq5HZZG/Q9EsEfYgJ+YEvc
57yKPH5NQnvsyl6909nvNzB07sbPJ6J5bsXkyUS4Smo1qPCQ6KhBmh2WREGFa1e0
kb8w9RpySlOz81qn9gJoJZCn+DM+cK7tg24k0ZKMM1Awekr+1P5TA9Q9VGSYHBJd
LMPVNKnSxrNLV0nlmBGX0uBkClxJCkycSyjubB4mlGULUuYIRRr+Cndj3jyJpuHm
GKKD+4ujAgMBAAECggEASFW/YmU0G6OwoKdxBiR8+yjNsqYfoQ+QMlzjwZEJL0Gq
insRbz5Spch+T6LO9WgxIPeOKFeAqvnfdThrU7LD3cXX+pc3nBHieiYG2YEOwJJB
U199draN3rhMZyjvJG1/tEftMWYLGTanTxjLRAtlaZAmEqeADeaV5heWrLZuE+HH
CaKbo7isy39vyqfGRa4ROe66N1pug8EHH7fPDqM4k8zMsLau80o6dc6HEKI0RB/H
HXbdaomXhuMuEkuifrwnyLPyVrw4LPkPlLi4BIWJBYVYXjosV0kTCg5HSWbITQ0J
jB48C3rM2SQuBrCiYu5tpluOx6Tsy5KrvKC04kRvGQKBgQD4PpQA49nweGQViMo8
rRSTPvh6R3S9xglvrOWrDpMZAOKTKsFx1GgoJOYIbCWYo+L42hyVWL/pxWbq1lvf
6UqPCoUqjP5U9TK5A2J8zJAo8erw3h5F/Bpz+DASluy0+3KhRJ5qrRAomhcZOtX+
5gl19r2hY2KjdSSEPA2Qr0JEWQKBgQD1JAqg4FnMVi5/Apz6idgC6QW5scMSKgzY
G+q2ehgGFvVA4Q8MezIFRBA/wsev+rh+WqWWuhJQKeWM49flIFQIGhlnoLTc3s/Z
CtBLf3d73WTpEJdQdyqR0YDVQ3pGj1UTm7aS/Fs+FaAw7d6Y32gL5LVb0vQ/FKGy
YKfGqi9AWwKBgHJUJ8fNKGdmmvmL+VA+ilZSTw/J7wsjtN7Y6yF/4eFHFhKfQ15Q
a/PpIoRIgnwtJnBjy3xA1oosnvyS4tdZ0zvTpYb2ToAEOWsaEvbVI6On3wM12Q10
UR6N9F3rYnLrx1xchPUuZV29sdutzDbL7RmGHMnCQwBzB/Fa0wiKnuNpAoGBAN8s
QMDVfusYSpw2tNMiSxXbLusveng+8BKO18/ot5ZTsFOwkRK71X4VyPVDTqhXiT7/
J2FhZOq2OdVaWGKwW9BEcnx1QjMSZgciYR9anFyX4haMlDUdSBQYt0FwfRFfzARd
7olCVY7gAUaKR+zE9uRdAv7lvpbvIYZTmGq05O+hAoGAQdrN2pk4P7l/hax5F7yo
hGUahXhPvN1OkI+772dFhjpQYxf02oKrdW/pNrTAoYyE9tCUUeZngUZ6SkN+TlJa
ouK1o4xnmMD2YhHhzmxyn8wlLB8KopMzCQ8WaooivlJbyXQVp6bq9UFaeQW0NtIB
tzMFGyiO+DvR4pO52uQLEBU=
-----END PRIVATE KEY-----"